#!/bin/bash

if [ -z $DBPSWD ]; then
	echo "Enter password for MySQL:"
	read DBPSWD
fi
CFGTAG="####>>>> GENERATED BY: BeyondEarthRP FiveM Config & DB Manager"

if [ -z $SOURCE ]; then
    SOURCE=~/REPO
fi

declare -a configs
OUT_CFG=$SOURCE/serverCfg_top
CONFIG=0

if [ -d "$SOURCE/configs" ]; then
    rm -rf $SOURCE/configs
fi
if [ -f "$SOURCE/server.cfg" ]; then
    rm -f $SOURCE/server.cfg
fi
if [ -f "$SOURCE/serverCfg_top" ]; then
    rm -f $SOURCE/serverCfg_top
fi

mkdir $SOURCE/configs
touch $SOURCE/server.cfg
cd $SOURCE

while read -r line <&3; do
    if [ ! -z "$line" ]; then
        CONF_TYPE=$(echo $line | cut -f1 -d:)
        DATA=$(echo $line | rev | cut -f1 -d: | rev)

        if [ $CONF_TYPE == "CONFIG" ]; then
            echo "$DATA >> $OUT_CFG"
            echo $DATA >> $OUT_CFG
            if [ "$OUT_CFG" != "$SOURCE/serverCfg_top" ]; then
                CONFIG=1
            fi
        elif [ $CONF_TYPE == "MYSQL" ]; then
            FILE=${DATA/<RESOURCES>/$SOURCE}

            #nano $FILE   #<- to edit the files first
            echo $FILE
            mysql -u root -p$DBPSWD essentialmode < $FILE
        elif [ $CONF_TYPE == "HEADER" ]; then
            # EXAMPLE:
            # HEADER:HEADER INFORMATION%FILE

            if [ $CONFIG != 0 ]; then
                # CLOSING OUT PREVIOUS CONFIG
                echo "" >> $OUT_CFG
                echo $CFGTAG >> $OUT_CFG
            else
                if [ "$OUT_CFG" != "$SOURCE/serverCfg_top" ]; then
                    rm $OUT_CFG
                fi
            fi

            # STARTING A NEW CONFIG
            HEADER_INFO=$(echo $DATA | cut -f1 -d%)
            HEADER_FILE=$(echo $DATA | rev | cut -f1 -d% | rev)
            OUT_CFG="$SOURCE/configs/$HEADER_FILE.cfg"
            OUT_CFG_ENTRY="configs/$HEADER_FILE.cfg"
            CONFIG=0

            touch $OUT_CFG
            configs+=("$OUT_CFG_ENTRY")

            echo "#######################################" > $OUT_CFG
            echo "# $HEADER_INFO" >> $OUT_CFG
            echo "#######################################" >> $OUT_CFG
        elif [ $CONF_TYPE == "######" ]; then #SUBHEADER
            # EXAMPLE:
            # SUBHEADER:PUT YOUR HEADER HERE

            echo "" >> $OUT_CFG
            echo "#||||||||||||||||||||||||||||||||||||||" >> $OUT_CFG
            echo "#|> $DATA" >> $OUT_CFG
            echo "#||||||||||||||||||||||||||||||||||||||" >> $OUT_CFG
        fi
    else
        echo ""
    fi
    echo ""
done 3< <(cat $SOURCE/serverCfg_data)
if [ $CONFIG != 0 ]; then
    # CLOSING OUT PREVIOUS CONFIG
    echo "" >> $OUT_CFG
    echo $CFGTAG >> $OUT_CFG
else
    rm $OUT_CFG
fi

timestamp=$(date +%s)
echo "#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#" > $SOURCE/server.cfg
echo "#> BEYOND EARTH ROLEPLAY" >> $SOURCE/server.cfg
echo "#> $timestamp" >> $SOURCE/server.cfg
echo "#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#" >> $SOURCE/server.cfg
echo "" >> $SOURCE/server.cfg
cat $SOURCE/serverCfg_net >> $SOURCE/server.cfg
if [ -f $SOURCE/serverCfg_top ]; then
    echo "writing the top of the config:"
    echo "    cat $SOURCE/serverCfg_top >> $SOURCE/server.cfg "
    cat $SOURCE/serverCfg_top >> $SOURCE/server.cfg
    echo "removing remnants..."
    echo "    rm $SOURCE/serverCfg_top"
    rm $SOURCE/serverCfg_top

fi
echo "" >> $SOURCE/server.cfg
echo "#######################################" >> $SOURCE/server.cfg
echo "# EXTERNAL CONFIGURATION FILES" >> $SOURCE/server.cfg
echo "#######################################" >> $SOURCE/server.cfg
for serverCfg in "${configs[@]}"
do
    echo "writing config line:"
    echo "    exec $serverCfg >> $SOURCE/server.cfg"
    echo "exec $serverCfg" >> $SOURCE/server.cfg
    echo ""
done
echo "done with nested configs."
echo ""
echo "writing footer config..."
echo "    cat $SOURCE/serverCfg_footer >> $SOURCE/server.cfg"
cat $SOURCE/serverCfg_footer >> $SOURCE/server.cfg
echo ""
echo "Finished."
